source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Core Libraries
def core()
  pod 'Moya-Gloss', :path => '../'
  pod 'Moya-Gloss/RxSwift', :path => '../'
  pod 'Moya-Gloss/ReactiveSwift', :path => '../'
end

# Testing Libraries
def testing()
  pod 'Quick', '~> 1.3'
  pod 'Nimble', '~> 7.3'
end

target 'Demo' do
  platform :ios, '9.0'
  core
end

target 'Tests' do
  platform :ios, '9.0'
  core
  testing
end
